### PR TITLE
manual pull

### PR DESCRIPTION
**Pull request by pohly**
This one used the new "combo-layer update --history" mode, which is supported
by combo-layer in OE-core master now. Against the original intention, the mode
is now the default, which is okay for us but might surprise others.

### CODE REVIEW

**Comment by pohly** [comment]
@igor-stoppa @incandescant pulling the updated meta-swupd into ostro causes a build failure for swupd server. For example: https://ostroproject.org/jenkins/job/build_beaglebone/1580/console

**Comment by kad** [comment]
more important, would it break other scripts that depend on combo-layer ?

**Comment by incandescant** [comment]
Should be fixed in meta-swupd master. I'd really like to stop carrying the 2.x recipes soon…

**Comment by pohly** [comment]
@kad: combo-layer works, just not as expected by some.

**Comment by kad** [comment]
I understand it works, just worried about result in target repository in some corner cases.

**Comment by pohly** [comment]
Pushed revised branch with additional commits in meta-swupd.

**Comment by kad** [comment]
btw, what is the reason for manual update?

**Comment by pohly** [comment]
Reason for manual update is the same as in all recent pulls: meta-intel-iot-middleware does not work with Yocto meta-java (see also PR #97). I keep adding that as explanation in the commit message, but do not always add it to the pull request - it's getting a bit tiresome to repeat myself :-/

**Comment by pohly** [comment]
retest this please 

"slave went offline" problem during the build.

**Comment by pohly** [comment]
Some (intermittent?) test failures on BeagleboneBlack (https://ostroproject.org/jenkins/job/test_beagleboneblack/1070/):
```
    oeqa.runtime.sanity.apprt_iotivity_node.SanityTestIotivityNode.test_require_iotivity_node
    oeqa.runtime.sanity.apprt_restapi.SanityTestRestApi.test_restapi_available_by_remote
```

Let's see if this is reproducable...

retest this please

**Comment by pohly** [comment]
Still a bit wary about the random test failure... something to watch out for. Merging now anyway.

**Pull request merged**
