### PR TITLE
Java upstream change CI test trigger

### PR DESCRIPTION
**Pull request by Valtis**
This pull request is purely for triggering CI testing - do not merge as it touches multiple meta layers.

We currently use a fork of meta-java. This pull request changes the meta-java to use the proper Yocto upstream, and contains required changes so that it actually builds. This requires changes in multiple meta layers (meta-ostro, meta-java, meta-ostro-fixes), which is problematic from CI testing point of view, as (as far as I know) there is no way of testing multiple pull requests to different layers as one change set. 

List of changes for those who are interested:

Meta-java layer is deleted and then recreated through combo-layer update. This unfortunately causes lots of noise, as they layer is fairly big and has tons of commits in its history. 

Meta-java whitelisting and Java package group have been modified as the Yocto upstream uses different openjdk-8 recipe with different name. Whitelist is also modified to whitelist different bootstrap VM, as the current VM requires X11 in distro features for some reason. Alternative VM is thankfully provided by the layer, and it works without issues on my machine at least. 

The openjdk recipe also has a patch that changes its build time requirements, and as a result we can drop ostro-x11.inc as X11 is no longer required for building openjdk. Openjdk however requires bbappend to change its flags, as -DFORTIFY_SOURCES requires at least -O, which is not used by default.

### CODE REVIEW

**Comment by Valtis** [comment]
Blacklisted several graphics related recipes that were no longer working due to the X11 workaround removal.

**Comment by kad** [comment]
retest this please

**Comment by Valtis** [comment]
Removed ostro-specific patches and pulled in latest meta-java, as these patches were accepted upstream. Effectively just reorders the way the patches are applied.

**Comment by Valtis** [comment]
I'm currently not actively working on this, so I'm closing it for now.

**Comment by Valtis** [comment]
retest this please

Reopened as I'm again working on this.

**Comment by Valtis** [comment]
@ereshetova Openjdk has two files that intentionally avoid optimizations (-O0) due optimizations potentially breaking things (see for example http://bugs.java.com/view_bug.do?bug_id=7142617). -D_FORTIFY_SOURCE on the other hand needs at least -O. I just silenced the warnings that this generates, as they were breaking the build due to -Werror. Is this OK from security point-of-view?

**Comment by ereshetova** [comment]
@Valtis, can you copy warnings here that I generates that I can take a look?

**Comment by Valtis** [comment]
@ereshetova 

/<build_dir_path>/sysroots/<architecture>/usr/include/features.h:331:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
|  #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
|     ^

**Comment by ereshetova** [comment]
@Valtis, per discussion with our team it should be fine to suppress the warning from security standpoint.

**Pull request closed without merging**
