### PR TITLE
update meta-swupd to current master

### PR DESCRIPTION
**Pull request by pohly**
This brings in several enhancements:
- Incremental builds even when starting from a clean build
  environment (reduces size of swupd repo and speeds up builds).
- Significant performance improvements.

### CODE REVIEW

**Comment by pohly** [comment]
Once this is merged, I also have some more commits for meta-ostro which then complete the current set of swupd improvements. However, I think this PR will already work by itself, because the commits in meta-ostro just clean up a few things.

**Comment by pohly** [comment]
@mythi Test results are almost clean, only Edison failed for some (unrelated?) reasons. Looks like the device became unavailable while testing (ssh connection errors).

Shall we wait for a retest or just merge?

**Comment by pohly** [comment]
retest this please

At least retesting only takes one hour for building now ;-}

**Comment by pohly** [comment]
@mythi @incandescant: all tests clean - let's merge the update meta-swupd into Ostro.

**Comment by mythi** [comment]
@pohly thanks a lot!

**Pull request merged**
