### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by igor-stoppa**
1) Move to 3.x swupd client
2) Change the helper that updates the EFI app

### CODE REVIEW

**Comment by igor-stoppa** [comment]
Note: I've tested many times 1) and it worked for me, but testing for 2) is still under work.

**Comment by pohly** [comment]
@igor-stoppa was this intentionally submitted against ostro-os instead of meta-ostro? You are only modifying meta-ostro, so you could have submitted there.

**Comment by pohly** [comment]
@igor-stoppa on IRC you mentioned that the current updater will (or may) fail in some cases? Can you explain in which cases, ideally in a JIRA entry so that the problem has a public, permanent record and can be triaged?

**Comment by igor-stoppa** [comment]
@pohly: ok, if this passes, I'll re-create it against meta-ostro

**Comment by pohly** [comment]
@igor-stoppa you mentioned that the "New efi combo updater" commit fixes a known bug and that we have a bug entry for it. Please add the "Fixes: IOTOS-xxxxx" line to the commit message.

**Comment by pohly** [comment]
Moved to https://github.com/ostroproject/meta-ostro/pull/247

**Pull request closed without merging**
