### PR TITLE
manual pull

### PR DESCRIPTION
**Pull request by pohly**

### CODE REVIEW

**Comment by pohly** [comment]
Failed once because of unrelated problems. Now the PR only contains the update meta-swupd from joshuagl/next.

**Comment by pohly** [comment]
retest this please

@ereshetova isafw again had a problem (https://ostroproject.org/jenkins/job/build_intel-quark/1997/console):
```
ERROR: Exception in plugin ISA_LicenseChecker process_report():
03:46:29.670 Traceback (most recent call last):
03:46:29.670   File "/var/lib/jenkins/ostro-worker-19-slot-0-OTusb/ostro-os/meta-security-isafw/lib/isafw/isafw.py", line 133, in call_plugins
03:46:29.670     method(*parameters, **keywords)
03:46:29.670   File "/var/lib/jenkins/ostro-worker-19-slot-0-OTusb/ostro-os/meta-security-isafw/lib/isafw/isaplugins/ISA_la_plugin.py", line 262, in process_report
03:46:29.670     return LicenseChecker.process_report()
03:46:29.670   File "/var/lib/jenkins/ostro-worker-19-slot-0-OTusb/ostro-os/meta-security-isafw/lib/isafw/isaplugins/ISA_la_plugin.py", line 127, in process_report
03:46:29.670     self.process_pkg_list()
03:46:29.670   File "/var/lib/jenkins/ostro-worker-19-slot-0-OTusb/ostro-os/meta-security-isafw/lib/isafw/isaplugins/ISA_la_plugin.py", line 145, in process_pkg_list
03:46:29.670     orig_pkg_name = line.split()[2]
03:46:29.670 IndexError: list index out of range
```

**Comment by pohly** [comment]
@kad okay to merge this manual update?

I'll follow up with Elena on the isafw failure separately.

**Comment by kad** [comment]
👍

**Pull request merged**
