### PR TITLE
manually update meta-intel-iot-middleware

### PR DESCRIPTION
**Pull request by pohly**

### CODE REVIEW

**Comment by pohly** [comment]
@tripzero this now leads to:
```
NOTE: Resolving any missing task queue dependencies
NOTE: multiple providers are available for runtime java2-runtime (openjre-8, openjdk-8)
NOTE: consider defining a PREFERRED_RPROVIDER entry to match java2-runtime
ERROR: Nothing RPROVIDES 'java-runtime' (but /var/lib/jenkins/workspace/build-recipe-selftests/ostro-os/meta-intel-iot-middleware/recipes-connectivity/tinyb/tinyb_0.3.3.bb RDEPENDS on or otherwise requires it)
```

We should define a PREFERRED_RPROVIDER (but I'm wondering whether that should be PREFERRED_PROVIDER). But the real error is that there's still a java-runtime dependency.

**Comment by pohly** [comment]
@tripzero I've pushed two commits which should fix the problem. If the build succeeds, we need  to submit them to their respective repo and re-generate this PR.

**Comment by pohly** [comment]
@tripzero my patches addressed the original problems, but now it fails while compiling tinyb.

Do we need that?

**Comment by mircea** [comment]
https://github.com/tripzero/meta-intel-iot-middleware/commits/master contains updated MRAA, UPM and TinyB recipes (fixing the meta-java incompatibility of TinyB). This has not yet been pulled into http://git.yoctoproject.org/cgit/cgit.cgi/meta-intel-iot-middleware/ .

@tripzero @andreivasiliu2211

**Comment by pohly** [comment]
https://github.com/ostroproject/meta-intel-iot-middleware/commits/master has several fixes, now I just need to refresh this pull request with the new commits.

**Comment by pohly** [comment]
Updated PR pushed, let's see how testing goes...

**Comment by pohly** [comment]
Now upm fails to compile (https://ostroproject.org/jenkins/job/build_beaglebone/1641/console being just one example, same for edison and intel-core2-32):
```
/var/lib/jenkins/ostro-worker-14-slot-2-ACHdC/ostro-os/build/tmp-glibc/sysroots/x86_64-linux/usr/include/python3.5m/pyport.h:811:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
00:13:07.587 |  #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
```

On 64 bit (https://ostroproject.org/jenkins/job/build_intel-corei7-64/1641/console) it gets further, but then fails with:
```
Collected errors:
  * satisfy_dependencies_for: Cannot satisfy the following dependencies for packagegroup-devkit:
  * 	libpython3.5m1.0 (>= 3.5.1) * 
  * opkg_install: Cannot install package packagegroup-devkit.
```

This now blocks integration, as I don't know enough about compilation of upm to come up with a quick fix. If someone wants to investigate, you can fetch the pohly:m-i-i-m-migration branch and directly build from that (it's a full ostro-os repo with the latest meta-intel-iot-middleware).

**Comment by tripzero** [comment]
The 32bit error we keep on seeing randomly.  It has to do with ci using python3 on the host.  It's been a difficult problem to fix because it randomly disappears as often as it pops up.

I'll take a look at both.

**Comment by kad** [comment]
default version of python on all builders is python 2.7.11. Even if it's somehow interfering with host OS during build, it's really BUG in the recipes.

**Comment by pohly** [comment]
@tripzero is testing something in PR #104

**Comment by pohly** [comment]
Testing of fixes for the compile problems happens in PR #104.

**Comment by pohly** [comment]
I'm merging this one here instead of PR #107. Both would (eventually) have the same effect, but this one here has some advantages:
- testing actually completed successfully, in contrast to PR #107 which had some unrelated problems
- here we have proof that the combo-layer.conf change is working (because combo-layer was used to import the new commits)

**Comment by kad** [comment]
test builds not supposed to be merged.

**Comment by pohly** [comment]
It stopped being a test build a while ago, I merely forgot to unset the label.

**Pull request merged**
