### PR TITLE
test build: try some fixes for CI branch

### PR DESCRIPTION
**Pull request by pohly**
https://github.com/ostroproject/ostro-os/pull/116 fails for various
reasons. This branch here has additional commits addressing some of these
failures.

### CODE REVIEW

**Comment by tripzero** [comment]
Seems like adding -fpie -shared to the build products that are failing should also work.

**Comment by pohly** [comment]
@tripzero yes, reordering command line parameters via Makefile patches would also  work. But I was looking for a simple solution first.

**Comment by tripzero** [comment]
build is stuck?

**Comment by pohly** [comment]
@tripzero meta-swupd is extremely slow in this test build. We already discussed/analyzed it on IRC today, but didn't come to a conclusion. However, the build of openjdk has worked, which is what matters more in the PR.

**Comment by okartau** [comment]
very slow or not progressing, how to tell the difference... I terminated jobs after 28h or running. That was the job where I traced pseudo and tar progress on a builder (it was 17h run time then). tar processes were active moving one 1.7 G tree around back then, but for some reason job did not got forward from that same step.

**Comment by pohly** [comment]
All local fixes merged elsewhere, replaced by PR #144.

**Pull request closed without merging**
