### PR TITLE
manual pull

### PR DESCRIPTION
**Pull request by pohly**
Another manual pull while waiting for various issues to be resolved. See final
commit message for details.

### CODE REVIEW

**Comment by kad** [comment]
👎 Please do manual combo-layer without history.

**Comment by pohly** [comment]
@kad I verified that import without history also works. Which version we merge into ostro-os is orthogonal to running that test. But I'm tired of arguing with you, so I'll just force-push the less useful merge without history.

**Comment by pohly** [comment]
@kad okay to merge now? I've addressed your concern.

**Comment by kad** [comment]
Yes, ok.

**Pull request merged**
