### PR TITLE
manual pull

### PR DESCRIPTION
**Pull request by pohly**
New meta-intel-iot-middleware still doesn't compile with Ostro OS
master (see PR #97). OE-core also fails (mkelfimage, test runner).
See last commit for details.

### CODE REVIEW

**Comment by pohly** [comment]
Build kicked off with OE-core that fixes useradd: https://ostroproject.org/jenkins/job/ostro-os_pull-requests/664/

However, compilation of mkelfimage may fail for Beaglebone because of "mkelfimage: obey LDFLAGS, sort out HOST_ flags".

**Comment by pohly** [comment]
Another test build kicked off with "mkelfimage: obey LDFLAGS, sort out HOST_ flags" reverted: https://ostroproject.org/jenkins/job/ostro-os_pull-requests/665/

**Comment by kad** [comment]
Are you manually injecting commits on top of output of combo-layer ?

**Comment by pohly** [comment]
Yes, for a test build. I'm not going to merge it like that of course.

**Comment by kad** [comment]
Then please always reflect that with labels if it's not production build.

**Comment by pohly** [comment]
@kad I use the "test-build". You were just commenting while I was still updating the PR.

**Comment by kad** [comment]
flag should be set at the time when you were writing comment "Another test build kicked off with "mkelfimage: obey LDFLAGS, sort out HOST_ flags" reverted".

**Comment by pohly** [comment]
@kad: you commented one minute after I left that comment. Cut me some slack, okay?

**Comment by kad** [comment]
Every manual pull request to this repository sounds fishy by default, except they are clearly marked as test-build. That one got test-build label assigned only after my comment. That's why I reminded about timing of events.

**Comment by pohly** [comment]
@kad and I pointed out that the timing was so that your comment overlapped with me working with this PR and the resulting Jenkins jobs. Next time please leave a bit more time, okay? It's not going to be merged minutes after creating it.

**Comment by kad** [comment]
@pohly what I'm trying to say: if you see that you're doing something manually, and it's not final content, set labels **before** you press "comment" button. **not after**. I understand it's manual workflow that is error prone. But get as a good habit of first setting labels, then push/comment.

**Comment by pohly** [comment]
Genuine "combo-layer update" without manual changes. Could be merged if it passes testing.

test this please

**Pull request merged**
