### PR TITLE
swupd: update /etc

### PR DESCRIPTION
**Pull request by pohly**
Test build with one pending patch for meta-swupd and several for meta-ostro.

Local builds with limited bundle content (just valgrind) shows that
"swupd verify" passes for the os-core although swupd client is configured
such that it no longer excludes /etc.

### CODE REVIEW

**Comment by pohly** [comment]
@incandescant please review the PR and merge commit 6940105.

@rojkov if you continue testing swupd, perhaps do it based on this branch? I included your Smack transmute fix, because it is not in ostro-os yet (not even the CI integration branch, which is the base for this PR).

**Comment by rojkov** [comment]
Yes, I noticed that so I've edited my bblayers.conf to point to the tips of meta-swupd and meta-ostro.

**Comment by pohly** [comment]
@rojkov I forgot to ask explicitly, but please also review whether this approach here makes sense for Ostro.

@igor-stoppa please also have a look.

**Comment by incandescant** [comment]
6940105 has been merged to meta-swupd master

**Comment by pohly** [comment]
Replaced by https://github.com/ostroproject/meta-ostro/issues/118

**Pull request closed without merging**
