### PR TITLE
ostro-os: manual combo-layer update from all layers

### PR DESCRIPTION
**Pull request by mythi**
This is a manual combo-layer update from all layers. We are
bypassing the automated pipeline to avoid breakage when merging
certain PRs in meta-ostro*, meta-appfw, and meta-iotqa layers
too early. This can be seen as an attempt to create an atomic
(or close to atomic) operation.

The combo-layer update includes commits from master-next of
the aforementioned layers. The plan is that once this update
is merged, master-next of meta-ostro, meta-ostro-fixes, meta-appfw,
and meta-iotqa gets pushed to master (this operation also closes
the relevant PRs).

The update is huge, primarily because we've not pulled from
openembedded-core and bitbake repositories for a while. The
integration criteria is rather low considering how big changes
this update brings: builds must be OK and all sanity tests on
all platforms must pass.

### CODE REVIEW

**Comment by kad** [comment]
I'll look a bit more closely, but first few comments:
1. better not to use label "master-next" to avoid false assumptions.
2. branches that were used to pull changes to combo-layer tool, would be better to explicitly push temporarily to those repositories, to control that they would need to be rebased in the future due to other merges into layers.
3. PR message would be good to have references to PRs in repositories, this would help tracking on which repos actually should be closed after this jumbo PR accepted.

**Comment by kad** [comment]
I'm worried about those random issues. :( fearing that it might be again similar to previous binutils instabilities.

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
@kad I've addressed your feeback in the commit message. Build #70 was good but I'll trigger one more build (because of the commit message update)

**Comment by pohly** [comment]
+1 for merging.

One further comment, though: @mythi confirmed that the commits that will get pushed to the individual components will not always (never?) have the usual non-ff merge commit that we get when accepting a pull requests in Github. This implies that when looking at the updated individual components, it will be less obvious who merged them.

IMHO it would be better to add a non-ff merge with an explanation that this is part of a larger manual update, like it was done in the commit message of this merge here. But that's not a showstopper, so  please go ahead.

**Comment by mythi** [comment]
#71 build also good. two subsequent builds OK so ready to merge. new masters updated.

**Comment by mythi** [comment]
On Fri, Mar 11, 2016 at 10:45 AM, Patrick Ohly wrote:

> IMHO it would be better to add a non-ff merge with an explanation that
> this is part of a larger manual update, like it was done in the commit
> message of this merge here. But that's not a showstopper, so please go
> ahead.
>
>
This is worth to think if (when) something similar is needed. On the
contrary, the feedback I got when pushing some fixes in meta-soletta was:
they prefer PRs for review only but the commits get pushed directly to
avoid these merge commits.

**Comment by pohly** [comment]
meta-soletta has a different policy then than Ostro. In Ostro, we discussed this a while back and come to the conclusion that we want to have the non-ff merge commits, because they record additional information.

**Pull request merged**
