### PR TITLE
meta-swupd: revert to edf0a04d8dc

### PR DESCRIPTION
**Pull request by pohly**
The changes since then introduced code which cannot handle the xattrs
that Ostro OS relies upon. Fixing that problem depends on enhancing
OE-core. Even if these fixes were available soon, importing them into
Ostro OS would be blocked by the unsolved problems with Python3 in
Ostro OS.

That only leaves reverting the changes in Ostro OS and (if necessary)
branching meta-swupd and following that new branch in Ostro OS. For
now we just revert to the (presumably) last good revision.

Fixes: IOTOS-1677

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>

### CODE REVIEW

**Comment by pohly** [comment]
retest this please

**Comment by pohly** [comment]
retest this please

isafw index out of range

**Comment by pohly** [comment]
@igor-stoppa do you agree that reverting to this revision of meta-swupd is the right direction? Should we merge it today for our next snapshot, or wait until you have done more testing with the revision?

**Comment by igor-stoppa** [comment]
@pohly yes, let's revert. I still need testing, but if it's clear that the current implementation won't be fixed in time for our needs, let's revert it for now.
I'll comment later if I find any issue, but this will save some time.

**Comment by pohly** [comment]
retest this please

isafw again (needs https://github.com/01org/meta-security-isafw/pull/63)

**Pull request merged**
