### PR TITLE
ostro-os: manual combo-layer update from bitbake

### PR DESCRIPTION
**Pull request by mythi**
We are seeing a race condition in CI master builds caused by a bitbake
change that dropped lockfiles for file:// urls. CI master builders
use a common mirror and with no proper locking try_mirror_url
fails with a race.

The problem is fixed in rev: 913b6ce22cd50eac96e8937c5ffc704bfce2c023
and pulled in by this manual combo-layer update.

### CODE REVIEW

**Comment by kad** [comment]
I would recommend to pull HEAD of master instead of individual commit. there are other fixes there that are beneficial to us. E.g. 69ef6c8a9db02bfa0e3fac72481ec26586a29a01

**Comment by mythi** [comment]
I'm trying to go with minimal changes here. 69ef6c8a9db02bfa0e3fac72481ec26586a29a01 is important but not fixing the issue we see as a whole so I'd propose we go with this PR as it is.

**Comment by okartau** [comment]
retest this please

**Comment by mythi** [comment]
after a short chat with @kad we agreed to pull the latest master from bitbake as it's already labeled as the next bitbake release. 

force pushed an update.

**Pull request merged**
