### PR TITLE
toybox: test build

### PR DESCRIPTION
**Pull request by pohly**
Do not merge, experimental and not really targetted for ostro-os.

### CODE REVIEW

**Comment by pohly** [comment]
retest this please

**Comment by pohly** [comment]
First test build was successful, but toybox support needs further work and manual testing, so closing this.

**Comment by pohly** [comment]
retest this please

"Slave went offline during the build"

**Comment by Valtis** [comment]
retest this please

Galileo tests have  failed twice due to wifi tests getting stuck. However, the tests were run on the same physical device. I blacklisted the device and now I want to see if this is hardware or software issue.

**Comment by Valtis** [comment]
Looks like the Galileo test got stuck again during wifi tests. These lines keep repeating in the serial log:

[1459933385.78] iwlwifi 0000:01:00.0: L1 Disabled - LTR Disabled
[1459933388.49] iwlwifi 0000:01:00.0: L1 Disabled - LTR Disabled
[1459933388.51] iwlwifi 0000:01:00.0: L1 Disabled - LTR Disabled
[1459933388.74] iwlwifi 0000:01:00.0: L1 Disabled - LTR Disabled
[1459933388.74] IPv6: ADDRCONF(NETDEV_UP): wlp1s0: link is not ready

**Comment by pohly** [comment]
Let's focus on stateless first. No need to keep testing this.

[skip ci]

**Comment by kad** [comment]
no activity for long time. let's close that test build. we can reopen it once new changes for this topic would be made.

**Pull request closed without merging**
