### PR TITLE
meta-java: Switch over to Yocto upstream

### PR DESCRIPTION
**Pull request by Valtis**
This pull request deletes the old meta-java directory and replaces it with the yocto version via manual combo layer update 

This pull request depends on https://github.com/ostroproject/meta-ostro/pull/149, which temporarily removes meta-java from builds to avoid any build breakage.

Is dependency for https://github.com/ostroproject/meta-ostro/pull/150

Signed-off-by: Erkka Kääriä <erkka.kaaria@intel.com>

### CODE REVIEW

**Comment by pohly** [comment]
Not directly related to this PR, but might as well ask here: why is rhino such an old version? Upstream distinguishes between "qualified" releases (which are very old, but even considering just those, R4 has been replaced by R5), and normal releases (much more recent, latest is 1.7.7.1).

From a distro and maintenance perspective, using a recent release would be better. Not a blocker for merging thus, just wondering.

**Comment by Valtis** [comment]
I imagine (although can't say for sure) that it's just that no one has bothered updating it. AFAIK it provides a Javascript interpreter for Java and maybe that use case just isn't that common for embedded systems.

**Comment by pohly** [comment]
Can we disable rhino?

**Comment by Valtis** [comment]
The dependency seems to be for the native rhino only (icedtea7-native), so removing it altogether shouldn't be impossible. 

Although if it only used during build, does it need to be disabled?

**Comment by msivosuo** [comment]
As a rule of thumb if something is not needed it's better to remove it and reduce Ostro BOM.

**Comment by pohly** [comment]
@mythi why was rhino included in our checklist when it is only as native package? Another false entry that we can ignore for now?

**Comment by pohly** [comment]
@Valtis we can be a bit more relaxed about build tools, but as @msivosuo said, it is better and easier to not have it show up at all.

**Comment by Valtis** [comment]
Rhino was a dependency for the previous openjdk recipe; the Yocto upstream uses a different recipe, and it seems it does not use rhino by default.

Also, I tried removing rhino-native from icedtea7 (--without-rhino), but it turns out it is a dependency for other native tools as well. I'll investigate if it is possible to remove it.

**Comment by Valtis** [comment]
Two recipes (icedtea7-native, bsf-native) needs some modifications, but otherwise it seems rhino-native could also be removed from the bootstrap process.

I'll modify the PRs to use rhino-native as a short term solution. I will then submit a patch to upstream that removes rhino-native from the bootstrap process, which allows us to remove it from the white list altogether.

**Pull request closed without merging**
