### PR TITLE
combo-layer.conf: switch to updating with history by default

### PR DESCRIPTION
**Pull request by pohly**
The new "update with history" mode in combo-layer is now in OE-core.
See commit message for the reason why that is useful.

### CODE REVIEW

**Comment by pohly** [comment]
@kad this is one of those ostro-os changes where an explicit +1 is desirable ;-}

**Comment by kad** [comment]
I would keep it with False until we actually get to the point where again upstream repo has non-linear history. It's good that workaround can be used, but if upstream considered to be not switching it by default, I also don't see reasons for us to keep it active all the time. So far, this state was able to catch problems with our not so well maintained repos.

**Comment by pohly** [comment]
@kad have you seen the reasons I mentioned for using this mode besides the one about being less strict about our upstream history?

I consider those enough to use the new mode. Not being force to serialize upstream repo's history is just the icing on the cake.

**Comment by kad** [comment]
I saw reasons, but in general, "if it works - don't touch" principle. We had thing working before for quite some time, and in scenarios where it was failing, it was really catching human mistakes.
Thus I'd rather keep default setting without workaround to be close to what Poky is doing.
If OE would decide to make this mode default, well, we will follow.

**Comment by pohly** [comment]
In principle I agree with "never change a running system", but in this case I think we can and should improve our workflow and the resulting combined repo.

Our workflow in the component repos is different from what OE does (Github merges vs. master-next and fast-forward), so what works well for OE does not necessarily work equally well for us.

I still prefer to use the new mode by default. That way we also know that it works when we need it. If it does not work, we can still fall back to a manual update without history.

But that is very unlikely: please remember that as a test, I had re-imported all of ostro-os since setting up the repo using the new method and a full diff against the same import using the old method never found any differences. See https://lists.ostroproject.org/pipermail/ostro-dev/2016-April/000372.html

**Comment by kad** [comment]
@pohly it's not about difference. It's more about ability to detect if some of repos are not in best shape.
I'm ok to enable that mode for upstream repos where we don't have control over (e.g. yocto).
But for repos under project control, I'd like to see failures if something done wrong.

As for difference with Yocto's "master-next" vs. github merges, it's not relevant here. We can also do FF merge for PRs, but it wouldn't gain us much value.

**Comment by pohly** [comment]
@kad I disagree about the importance of "ability to detect if some of repos are not in best shape" and the definition of what "best shape" actually means.

My point about Github merges was that they *have* value and therefore preserving them is useful, both in the upstream repo and the combined repo. The value is the information that a certain set of commits were tested together.

As we two are not reaching a conclusion, let's ask others for their opinion. I'll raise awareness of this PR in the mail thread about the topic.

**Comment by kad** [comment]
You can ask opinion in mailing list, but please don't move discussion away from code.

**Comment by ipuustin** [comment]
I think that combo-layer should be able to work with any upstream git repositories, whether or not they agree on "Ostro git style guide" or not. Even for our internal repositories, rewriting history on public master branches to get them to be linear again is questionable. (This is not to say that non-linear trees are better; they are not. Sometimes we just will end up having them, like we did with meta-intel-iot-middleware some time ago.)

I think that validating that our own repositories have linear history could be done with an extra check in CI, even without counting on combo-layer to fail. We could later add even more sanity tests to this extra check, if we so wish.

**Comment by kad** [comment]
@ipuustin practically right now combo-layer playing the role of that "extra" check. Maintainers of ostro-os repository are able to override it by manual pull requests at any time, but switching off this check at the moment doesn't make sense in my opinion. Implementing something in additional, would only complicate things, without much gain, as the only moment where we can intercept those, is between changes merged in our repos and before PR to ostro-os created by upstream-monitor.

**Comment by pohly** [comment]
@kad the "can this PR be imported with combo-layer" check only runs for PRs which actually get tested. We skip that testing for doc PRs (and for good reasons). We also skip the test when merging PRs without re-testing (again, for good reasons, because otherwise we end up with merging one PR per hour or even less).

So if we are serious about "our repos must be serializable", then we need a different approach for testing that. And just to be clear, I personally don't see enough value in that to justify spending any additional work on it - in particular when already busy people like the integrator (currently me) have to do it.

@ipuustin you only commented on the "import non-linear history" aspect. What do you think about the other arguments that (in my opinion) make importing with history better than importing without?

Just to recap, those arguments are:
- listing history shows that commits where developed
  independently in the different components, instead of
  artificially showing them as if they had been developed
  one after the after (component "aaaa" before "bbbb", then "ccc", ...)
- bisecting becomes easier: when upstream repos only ensure consistency
  when merging into their "master" branches, then those merge
  commits are good candidates for test builds also in the combined
  repo
- more data mining can be done, for example showing who merged a commit
  and when

**Comment by kad** [comment]
@pohly you're mixing two different things. when you're saying "can this PR be imported with combo-layer", you actually mean testing of PR towards e.g. meta-ostro. I'm talking about step executed in upstream-monitor job. This one fired automatically once any branch in any of combo-layer needed repository changed. This one showing issues in upstream repos, and this is the place where defaults are consumed.

**Comment by pohly** [comment]
@kad Then it is even worse than I thought: I thought you were talking about those cases where non-linear history can be detected in time to do something about it. Running combo-layer in non-history mode during the upstream monitor job is the worst place for checking that our own repos are "in best shape", because if they aren't, it is too late to fix the problem (if we consider it a problem, which I'm not convinced of).

But the problem is indeed that we are mixing several different topics:
1. in what "shape" our repos should be
2. how to enforce that
3. how to import repos

There's no consensus about 1 (you care about linear history, I don't), for 2 we only have a check that runs too late, but because late is seen as better than none, all discussion about how we want to do 3 gets derailed because it is expected to do some error checking that belongs elsewhere.

My proposal for moving forward is:
* let's gather more opinions about 1, and if there is no clear trend, let's do what's easier to achieve
* if the result is that we need additional quality checks, implement them so that they actually run in time and all cases (but that effort should be taken into account when proposing that we need this)
* decide about the merits of "update with history" independently from using it to enforce linear history

**Comment by pohly** [comment]
BTW, my earlier comment was based on the observation (assumption?) that PR-testing involves a combo-layer run to import into the current ostro-os master. Is that not the case?

**Comment by ipuustin** [comment]
@pohly: the other points about preserving history for later analysis are good, I guess, but the beef is still the ability to merge upstream repositories automatically without imposing any git style requirements on them.

The testing of Ostro Project's own git repositories should be done with some other way than by using combo-layer, which accidentally breaks with non-linear repositories. :-) The repository checks are important -- we need to decide what we want to test and then do proper testing in the right places (individual layer repositories).

I vote for merging this PR. I plan to do that tomorrow if there are no further comments or objections.

**Comment by kad** [comment]
PR testing involves combo-layer. however, issue became visible only when PRs in individual repositories are merged using 3way merge conflict resolutions. GitHub sometimes hides this from UI, but if you do it in normal git client, it would be visible. Combo-layer invocation between individual layer repositories and combined repo is the only place where it is interception can happen for such cases.

**Comment by barbieri** [comment]
what about if we decide and use it for a while, review that decision if it doesn't work after 1-2 months?

AFAIU both @ipuustin and @pohly propose to go with it. Any issues to try that for couple of weeks and see if it works, @kad?

**Comment by kad** [comment]
I have no doubts that it would work. But at the same time it would hide issues in our repositories if it would be any. And that's the thing I'm trying to avoid.

**Comment by barbieri** [comment]
how to move this towards a decision? Should we email the list and call for +1/-1 voting on the proposal? The one with more votes proceeds and discussion is over for few months, then we can reevaluate.

**Comment by kad** [comment]
@barbieri I already provided option that would allow us to move forward: enable history mode only for repositories that we do not control directly.

For our own repositories (or global default) we can think only at time when some other means would be implemented to ensure that our repositories do not contain non-trivial merges.

Other arguments, like data collection can always happen on original source repositories, not on release repository.

So, as summary, in current form, this particular patch is explicit -2 from my side as owner of SCM and Infrastructure.

**Comment by pohly** [comment]
@kad configuring history mode only for individual repositories is not currently supported by combo-layer. It's "all or nothing". Supporting mixed mode would have made the implementation more complicated and fails to achieves one of the goals for the "with history" import: guaranteed full history, without having to distinguish between components.

As to "data collection can happen on original repositories" - anything goes, but it would be more complicated. "git bisect" works best (only?!) when done in one repo, too.

**Comment by kad** [comment]
If it is "all or nothing", then currently is "nothing". Until we implement better health check for our own repositories, or e.g. OE-core makes history mode default for Yocto Project.
In case of detected problems, we will look at each individual case and resolve manually.

**Pull request closed without merging**
