### PR TITLE
ostro-os: manual combo-layer update

### PR DESCRIPTION
**Pull request by mythi**
Update to IoTivity 1.2.0.

### CODE REVIEW

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
@nagineni Do you see any reason why the iotivity-node test fails (this is with 1.2.0)?

**Comment by mythi** [comment]
test this please

**Comment by rzr** [comment]
Do you have any hint  for:
```
255 != 0 : iotivity-node not in PATH or on target.
```

https://ostroproject.org/jenkins/job/test_minnowboardmax/1860/testReport/junit/oeqa.runtime.sanity.apprt_iotivity_node/SanityTestIotivityNode/test_require_iotivity_node/


Cc: @nagineni

https://github.com/ostroproject/meta-iot-web/pull/25

**Comment by mythi** [comment]
test this please

**Comment by nagineni** [comment]
> Do you have any hint for:

> 255 != 0 : iotivity-node not in PATH or on target.
> https://ostroproject.org/jenkins/job/test_minnowboardmax/1860/testReport/junit/oeqa.runtime.sanity.apprt_iotivity_node/SanityTestIotivityNode/test_require_iotivity_node/

Test case seems to be flaky.  I just checked running iotivity-node on the image and that produced no errors.

**Pull request closed without merging**
