### PR TITLE
ostro-os: manual combo-layer update

### PR DESCRIPTION
**Pull request by mythi**
This manual combo-layer update pulls in document changes from
meta-ostro, meta-intel/meta-ostro-bsp alignment, and test case
updates from meta-iotqa.

### CODE REVIEW

**Comment by mythi** [comment]
test this please

**Comment by pohly** [comment]
@mythi test failure on beaglebone: oeqa.runtime.sanity.apprt_restapi.SanityTestRestApi.test_restapi_available_by_remote

**Comment by mythi** [comment]
On Thu, Apr 28, 2016 at 10:53 PM, Patrick Ohly <notifications@github.com>
wrote:

> @mythi <https://github.com/mythi> test failure on beaglebone:
> oeqa.runtime.sanity.apprt_restapi.SanityTestRestApi.test_restapi_available_by_remote
>
>

Yes :( It was fine in an earlier PR though.

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
v2: updates from meta-ostro*

**Comment by pohly** [comment]
Probably also need https://github.com/ostroproject/meta-appfw/pull/5 and https://github.com/ostroproject/meta-ostro/pull/151

**Comment by mythi** [comment]
@pohly I'm merging this now to get the build started. I'll prepare another one for the rest.

**Pull request merged**
